export enum UserRole {
  ADMIN = 'ADMIN',
  GURU = 'GURU',
}

export interface UserActivity {
  timestamp: number;
  action: string; // e.g., 'LOGIN', 'CREATE_MODULE', 'LOGOUT'
  details: string;
}

export interface User {
  username: string;
  role: UserRole;
  password?: string; // Stored for admin monitoring (Prototype only)
  name?: string;
  nip?: string; // NIP or NUPTK
  school?: string;
  lastLogin?: number;
  activityLogs?: UserActivity[];
}

export interface TeacherProfile {
  name: string;
  nip: string;
  jobTitle: string;
  school: string;
}

export enum SubjectType {
  UMUM = 'Umum',
  AGAMA = 'Pendidikan Agama',
  SENI = 'Seni Budaya',
  MULOK = 'Muatan Lokal',
  KHUSUS = 'Khusus',
}

export type PaperSize = 'A4' | 'F4' | 'Letter';

export interface ModuleConfig {
  id: string;
  // Editable Identity Fields
  teacherName: string;
  teacherNip: string;
  schoolName: string;
  
  // Principal Info
  principalName: string;
  principalNip: string;
  
  // Time & Location
  academicYear: string;
  moduleDate: string; // YYYY-MM-DD
  
  grade: number; // 1-6
  subjectType: SubjectType;
  subjectName: string; // Specific subject name
  cp: string; // Capaian Pembelajaran
  tp: string; // Tujuan Pembelajaran
  approach: string; // Fixed: Deep Learning
  model: string;
  method: string;
  p5Theme: string;
  timeAllocation: string;
  createdAt: number;
  content?: string; // HTML/Markdown content generated by AI
  
  // Images (Base64)
  teacherSignature?: string; 
  principalSignature?: string;
  
  // Settings
  paperSize: PaperSize;
}

export interface P5Theme {
  name: string;
  description: string;
}

export interface LearningModel {
  name: string;
  description: string;
}

export interface LearningMethod {
  name: string;
  description: string;
}

export interface ResetRequest {
  id: string;
  username: string;
  name: string;
  school: string;
  timestamp: number;
  status: 'PENDING' | 'APPROVED' | 'REJECTED';
}